import os
import ast
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

class PPTGenerator:
    def __init__(self):
        key = os.getenv("GEMINI_KEY_1")
        if key:
            genai.configure(api_key=key)
        self.model = genai.GenerativeModel('gemini-1.5-flash')

    def _generate_outline(self, topic: str, slide_count: int, style: str = "professional"):
        prompt = f"""
        You are an expert presentation designer (Zoho/Canva level quality).
        Create a {slide_count}-slide presentation outline for: "{topic}"
        Style: {style}
        
        Return ONLY a Python list of dictionaries. NO markdown, NO explanation.
        Each dict must have:
        - "title": slide title
        - "content": bullet points separated by newlines
        - "layout": one of "title_slide", "content", "two_column", "image_focus", "quote", "closing"
        - "accent_color": hex color for the slide accent
        - "notes": speaker notes
        
        Example format:
        [
            {{"title": "Introduction", "content": "Point 1\\nPoint 2", "layout": "title_slide", "accent_color": "#7928CA", "notes": "Open with impact"}}
        ]
        """
        try:
            response = self.model.generate_content(prompt)
            outline_text = response.text.replace('```python', '').replace('```', '').strip()
            return ast.literal_eval(outline_text)
        except Exception as e:
            print(f"[PPT] Outline generation error: {e}")
            return [{"title": f"Slide {i+1}", "content": "Content pending", "layout": "content", "accent_color": "#7928CA", "notes": ""} for i in range(slide_count)]

    def generate_presentation(self, topic: str, slide_count: int = 5, style: str = "professional"):
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt
            from pptx.dml.color import RGBColor

            outline = self._generate_outline(topic, slide_count, style)
            prs = Presentation()

            # Title Slide
            title_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_layout)
            slide.shapes.title.text = topic.upper()
            slide.placeholders[1].text = "Generated by AXIOM Studio • Powered by Gemini AI"

            # Content Slides
            bullet_layout = prs.slide_layouts[1]
            for slide_data in outline:
                slide = prs.slides.add_slide(bullet_layout)
                slide.shapes.title.text = slide_data.get("title", "Slide")
                tf = slide.placeholders[1].text_frame
                tf.text = slide_data.get("content", "")

                # Add notes
                notes = slide_data.get("notes", "")
                if notes:
                    notes_slide = slide.notes_slide
                    notes_slide.notes_text_frame.text = notes

            output_dir = "outputs"
            os.makedirs(output_dir, exist_ok=True)
            safe_name = topic.replace(' ', '_').replace('/', '_')[:50]
            file_path = os.path.join(output_dir, f"{safe_name}.pptx")
            prs.save(file_path)
            return {"file_path": file_path, "outline": outline, "slide_count": len(outline) + 1}
        except ImportError:
            # python-pptx not installed, return outline only
            outline = self._generate_outline(topic, slide_count, style)
            return {"file_path": None, "outline": outline, "slide_count": len(outline), "warning": "python-pptx not installed. Outline generated but file not created."}

    def generate_outline_only(self, topic: str, slide_count: int = 5, style: str = "professional"):
        return self._generate_outline(topic, slide_count, style)
